
import 'package:kaj_ache/core/utils/translation_keys.dart';

const Map<String, String> bnBD = {
  // General
  TKeys.appName:           'কাজ আছে',
  TKeys.ok:                'ঠিক আছে',
  TKeys.cancel:            'বাতিল',
  TKeys.save:              'সংরক্ষণ',
  TKeys.edit:              'সম্পাদনা',
  TKeys.delete:            'মুছুন',
  TKeys.confirm:           'নিশ্চিত করুন',
  TKeys.back:              'ফিরে যান',
  TKeys.retry:             'আবার চেষ্টা করুন',
  TKeys.tryAgain:          'আবার চেষ্টা করুন',
  TKeys.change:            'পরিবর্তন করুন',
  TKeys.close:             'বন্ধ করুন',
  TKeys.thankYou:          'ধন্যবাদ',
  TKeys.starRating:        'তারকা',
  TKeys.warning:           'সতর্কতা',
  TKeys.enterCommentFirst: 'জমা দেওয়ার আগে একটি মন্তব্য লিখুন।',
  TKeys.commentPosted:     'মন্তব্য সফলভাবে পোস্ট হয়েছে!',
  TKeys.enterReplyFirst:   'জমা দেওয়ার আগে একটি উত্তর লিখুন।',
  TKeys.replyPosted:       'উত্তর সফলভাবে পোস্ট হয়েছে!',
  TKeys.loading:           'লোড হচ্ছে...',
  TKeys.noData:            'কোনো তথ্য পাওয়া যায়নি',
  TKeys.error:             'ত্রুটি',
  TKeys.success:           'সফল',
  TKeys.submit:            'জমা দিন',
  TKeys.search:            'খুঁজুন',
  TKeys.seeAll:            'সব দেখুন',
  TKeys.district:            'জেলা',
  TKeys.area:                'এলাকা',
  TKeys.selectDistrict:      'জেলা নির্বাচন করুন',
  TKeys.selectDistrictFirst: 'প্রথমে জেলা নির্বাচন করুন',
  TKeys.selectArea:          'এলাকা নির্বাচন করুন',
  TKeys.businessName:        'ব্যবসার নাম',
  TKeys.serviceCategory:     'সেবার ধরন',
  TKeys.experience:          'অভিজ্ঞতা',
  TKeys.serviceArea:         'সেবার এলাকা',
  TKeys.saveChanges:         'পরিবর্তন সংরক্ষণ করুন',

  // Auth
  TKeys.welcomeBack:      'স্বাগতম',
  TKeys.fullname:    'পুরো নাম',

  TKeys.email:            'ইমেইল',
  TKeys.phone:            'ফোন',
  TKeys.password:         'পাসওয়ার্ড',
  TKeys.phoneNumber:      'ফোন নম্বর',
  TKeys.forgotPassword:   'পাসওয়ার্ড ভুলে গেছেন?',
  TKeys.login:            'লগইন',
  TKeys.noAccount:        'অ্যাকাউন্ট নেই?',
  TKeys.signUp:           'সাইন আপ',
  TKeys.emailOrPhone:     'ইমেইল বা ফোন',
  TKeys.emailOrPhoneHint: 'আপনার ইমেইল বা ফোন নম্বর দিন',
  TKeys.inputRequired:    'এই ঘরটি পূরণ করা আবশ্যক',
  TKeys.inputInvalid:     'সঠিক ইমেইল বা ফোন নম্বর দিন',
  TKeys.passwordRequired: 'পাসওয়ার্ড দেওয়া আবশ্যক',
  TKeys.passwordMin:      'সর্বনিম্ন ৬টি অক্ষর',
  TKeys.resetPassword:       'রিসেট পাসওয়ার্ড',
  // Home
  TKeys.home:              'হোম',
  TKeys.whatService:       'আপনার কী সেবা দরকার?',
  TKeys.popularServices:   'জনপ্রিয় সেবাসমূহ',
  TKeys.allCategories:     'সব ক্যাটাগরি',

  // Technician Dashboard
  TKeys.dashboardSubtitle: 'আপনার সেবা পরিচালনা করুন এবং কর্মক্ষমতা পর্যবেক্ষণ করুন।',
  TKeys.todayOverview:     'আজকের সারসংক্ষেপ',
  TKeys.availableJobs:     'উপলব্ধ কাজ',
  TKeys.ongoing:           'চলমান',
  TKeys.earnings:          'আয়',
  TKeys.noAvailableJobs:   'এই মুহূর্তে কোনো কাজ নেই।\nরিফ্রেশ করতে নিচে টানুন।',
  TKeys.recentActivities:  'সাম্প্রতিক কার্যক্রম',
  TKeys.customer:          'গ্রাহক',
  TKeys.customerBudget:    'গ্রাহকের বাজেট',
  TKeys.request:           'অনুরোধ',
  TKeys.bids:              'বিড',
  TKeys.noBidsYet:         'এখনো কোনো বিড নেই',
  TKeys.bidPlaced:         'বিড দেওয়া হয়েছে',
  TKeys.postedBy:          'পোস্ট করেছেন',

  // Services
  TKeys.services:          'সেবাসমূহ',
  TKeys.categories:        'ক্যাটাগরি',
  TKeys.bookNow:           'বুক করুন',
  TKeys.serviceDetails:    'সেবার বিবরণ',
  TKeys.selectDate:        'তারিখ নির্বাচন করুন',
  TKeys.selectTime:        'সময় নির্বাচন করুন',
  TKeys.address:           'ঠিকানা',
  TKeys.bookingConfirm:    'বুকিং নিশ্চিত করুন',
  TKeys.bookingSuccess:    'বুকিং সফল হয়েছে!',

  // Orders
  TKeys.orders:            'অর্ডারসমূহ',
  TKeys.activeOrders:      'সক্রিয় অর্ডার',
  TKeys.pastOrders:        'পূর্ববর্তী অর্ডার',
  TKeys.orderDetails:      'অর্ডারের বিবরণ',
  TKeys.orderStatus:       'অর্ডারের অবস্থা',
  TKeys.cancelOrder:       'অর্ডার বাতিল করুন',
  TKeys.pending:           'অপেক্ষমাণ',
  TKeys.accepted:          'গৃহীত',
  TKeys.onTheWay:          'পথে আছেন',
  TKeys.inProgress:        'চলমান',
  TKeys.completed:         'সম্পন্ন',
  TKeys.cancelled:         'বাতিল',

  // Tracking
  TKeys.trackOrder:        'অর্ডার ট্র্যাক করুন',
  TKeys.workerOnTheWay:    'কর্মী পথে আছেন',

  // Chat
  TKeys.chat:              'চ্যাট',
  TKeys.messages:          'বার্তাসমূহ',
  TKeys.typeMessage:       'বার্তা লিখুন...',
  TKeys.send:              'পাঠান',

  // Payments
  TKeys.payment:           'পেমেন্ট',
  TKeys.paymentMethod:     'পেমেন্ট পদ্ধতি',
  TKeys.totalAmount:       'মোট পরিমাণ',
  TKeys.platformFee:       'প্ল্যাটফর্ম ফি',
  TKeys.jobBudget:         'কাজের বাজেট',
  TKeys.payNow:            'এখন পরিশোধ করুন',
  TKeys.transactions:      'লেনদেনসমূহ',
  TKeys.cash:              'নগদ',
  TKeys.bkash:             'বিকাশ',
  TKeys.nagad:             'নগদ',

  // Reviews
  TKeys.reviews:           'রিভিউসমূহ',
  TKeys.writeReview:       'রিভিউ লিখুন',
  TKeys.rating:            'রেটিং',
  TKeys.yourReview:        'আপনার রিভিউ',

  // Notifications
  TKeys.notifications:     'বিজ্ঞপ্তিসমূহ',
  TKeys.markAllRead:       'সব পঠিত হিসেবে চিহ্নিত করুন',
  TKeys.noNotifications:   'কোনো বিজ্ঞপ্তি নেই',

  // Profile
  TKeys.profile:           'প্রোফাইল',
  TKeys.editProfile:       'প্রোফাইল সম্পাদনা',
  TKeys.myProfile:         'আমার প্রোফাইল',
  TKeys.workerProfile:     'কর্মীর প্রোফাইল',
  TKeys.language:          'ভাষা',
  TKeys.theme:             'থিম',
  TKeys.darkMode:          'ডার্ক মোড',
  TKeys.lightMode:         'লাইট মোড',
  TKeys.settings:          'সেটিংস',

  // Auth (extended)
  TKeys.passwordResetSuccess:   'আপনার পাসওয়ার্ড সফলভাবে রিসেট হয়েছে।',
  TKeys.createNewPassword:      'আপনার অ্যাকাউন্টের জন্য একটি নতুন পাসওয়ার্ড তৈরি করুন।',
  TKeys.newPassword:            'নতুন পাসওয়ার্ড',
  TKeys.newPasswordRequired:    'নতুন পাসওয়ার্ড আবশ্যক',
  TKeys.confirmPassword:        'পাসওয়ার্ড নিশ্চিত করুন',
  TKeys.confirmPasswordRequired:'পাসওয়ার্ড নিশ্চিতকরণ আবশ্যক',
  TKeys.passwordsDoNotMatch:    'পাসওয়ার্ড মিলছে না',
  TKeys.enterOtp:               'অনুগ্রহ করে ৬-সংখ্যার ওটিপি দিন',
  TKeys.accountVerified:        'আপনার অ্যাকাউন্ট সফলভাবে যাচাই করা হয়েছে।',
  TKeys.verifyOtp:              'ওটিপি যাচাই করুন',
  TKeys.otpSentInfo:            'আপনার ফোন বা ইমেইলে পাঠানো ৬-সংখ্যার কোডটি দিন।',
  TKeys.verify:                 'যাচাই করুন',
  TKeys.resendOtp:              'ওটিপি পুনরায় পাঠান',
  TKeys.createAccount:          'অ্যাকাউন্ট তৈরি করুন',
  TKeys.registerSubtitle:       'কাজ আছে ব্যবহার চালিয়ে যেতে নিবন্ধন করুন',
  TKeys.accountType:            'অ্যাকাউন্টের ধরন',
  TKeys.buyer:                  'ক্রেতা',
  TKeys.service:                'সেবা',
  TKeys.enterFullName:          'আপনার পুরো নাম লিখুন',
  TKeys.nameRequired:           'নাম আবশ্যক',
  TKeys.enterEmail:             'আপনার ইমেইল লিখুন',
  TKeys.emailRequired:          'ইমেইল আবশ্যক',
  TKeys.enterValidEmail:        'একটি সঠিক ইমেইল লিখুন',
  TKeys.enterPhone:             'আপনার ফোন নম্বর লিখুন',
  TKeys.phoneRequired:          'ফোন নম্বর আবশ্যক',
  TKeys.enterValidPhone:        'একটি সঠিক ফোন নম্বর লিখুন',
  TKeys.haveAccount:            'ইতিমধ্যে অ্যাকাউন্ট আছে?',

  // Profile (extended)
  TKeys.completeProfile:        'প্রোফাইল সম্পূর্ণ করুন',
  TKeys.saveProfile:            'প্রোফাইল সংরক্ষণ করুন',
  TKeys.buyerAccount:           'ক্রেতা অ্যাকাউন্ট',
  TKeys.serviceProvider:        'সেবা প্রদানকারী',
  TKeys.basicInformation:       'মৌলিক তথ্য',
  TKeys.buyerDetails:           'ক্রেতার বিবরণ',
  TKeys.jobsPosted:             'পোস্ট করা কাজ',
  TKeys.totalSpent:             'মোট খরচ',
  TKeys.trustScore:             'বিশ্বাস স্কোর',
  TKeys.serviceProviderDetails: 'সেবা প্রদানকারীর বিবরণ',
  TKeys.category:               'ক্যাটাগরি',
  TKeys.completedJobs:          'সম্পন্ন কাজ',

  // Booking
  TKeys.describeProblemError:   'অনুগ্রহ করে আপনার সমস্যা বর্ণনা করুন।',
  TKeys.addressRequired:        'ঠিকানা আবশ্যক।',
  TKeys.pickDateError:          'অনুগ্রহ করে একটি তারিখ নির্বাচন করুন।',
  TKeys.selectTimeSlotError:    'অনুগ্রহ করে একটি সময় নির্বাচন করুন।',
  TKeys.budgetMinError:         'কমপক্ষে ১০০ টাকা বাজেট নির্ধারণ করুন।',
  TKeys.validation:             'যাচাই',
  TKeys.bookingSuccessful:      'বুকিং সফল',
  TKeys.bookingSubmittedMsg:    'আপনার বুকিং সফলভাবে জমা হয়েছে। প্রদানকারীরা এখন আপনার অনুরোধে বিড করতে পারবেন।',
  TKeys.viewMyBookings:         'আমার বুকিং দেখুন',
  TKeys.bookService:            'সেবা বুক করুন',
  TKeys.serviceScope:           'সেবার পরিধি',
  TKeys.logistics:              'লজিস্টিকস',
  TKeys.payConfirm:             'পরিশোধ ও নিশ্চিত করুন',
  TKeys.minimumPrice:           'সর্বনিম্ন মূল্য',
  TKeys.defineScope:            'পরিধি নির্ধারণ করুন',
  TKeys.defineScopeSubtitle:    'আপনার ঠিক কী কাজ প্রয়োজন তা জানান।',
  TKeys.selectSubservices:      'সাব-সার্ভিস নির্বাচন করুন (ঐচ্ছিক)',
  TKeys.problemDetails:         'সমস্যার বিবরণ *',
  TKeys.problemDetailsHint:     'সমস্যাটি বিস্তারিত বর্ণনা করুন। যত বেশি জানাবেন, তত ভালো বিড পাবেন...',
  TKeys.logisticsBudget:        'লজিস্টিকস ও বাজেট',
  TKeys.logisticsSubtitle:      'কোথায়, কখন এবং কত?',
  TKeys.serviceAddress:         'সেবার ঠিকানা *',
  TKeys.addressHint:            'বাসা #, রোড, এলাকা...',
  TKeys.city:                   'শহর',
  TKeys.dateLabel:              'তারিখ *',
  TKeys.pickDate:               'তারিখ নির্বাচন',
  TKeys.pickTime:               'সময় নির্বাচন',
  TKeys.timeSlot:               'সময় *',
  TKeys.minBudgetError:         'সর্বনিম্ন বাজেট ১০০ টাকা',
  TKeys.transactionId:          'ট্রানজেকশন আইডি',
  TKeys.transactionIdHint:      'পেমেন্টের ট্রানজেকশন আইডি দিন',
  TKeys.transactionIdRequired:  'ট্রানজেকশন আইডি আবশ্যক',
  TKeys.maxBudgetLabel:         'সর্বোচ্চ বাজেট (টাকা) *',
  TKeys.budgetHint:             'যেমন ২০০০',
  TKeys.maxBudgetInfo:          'প্রদানকারীরা এই পরিমাণের বেশি বিড করবে না।',
  TKeys.reviewPay:              'পর্যালোচনা ও পরিশোধ',
  TKeys.bookingFeeInfo:         'একজন টেকনিশিয়ান নির্বাচনের পর বুকিং ফি পরিশোধ করুন।',
  TKeys.maxBudgetShort:         'সর্বোচ্চ বাজেট',
  TKeys.bookingFee:             'বুকিং ফি',
  TKeys.refundableInfo:         'কোনো প্রদানকারী না পাওয়া গেলে ফেরতযোগ্য',
  TKeys.processing:             'প্রসেসিং...',
  TKeys.confirmPay500:          'নিশ্চিত করুন ও পরিশোধ করুন',
  TKeys.markTaskComplete:       'কাজ সম্পন্ন হিসেবে চিহ্নিত করবেন?',
  TKeys.startBookingConfirm:    'এই বুকিং শুরু করবেন?',
  TKeys.makeInProgress:         'চলমান করুন',
  TKeys.taskCompleted:          'কাজ সম্পন্ন',
  TKeys.taskCompletedMsg:       'বুকিংটি সম্পন্ন হিসেবে চিহ্নিত হয়েছে।',
  TKeys.technicianBooked:       'টেকনিশিয়ান সফলভাবে বুক হয়েছে',
  TKeys.bookingIdMissing:       'বুকিং আইডি পাওয়া যায়নি।',
  TKeys.reviewService:          'সার্ভিস রিভিউ করুন',
  TKeys.rateTechnician:         'টেকনিশিয়ান রেটিং দিন',
  TKeys.serviceReviewSubmitted: 'আপনার সার্ভিস রিভিউ জমা হয়েছে।',
  TKeys.techRatingSubmitted:    'আপনার টেকনিশিয়ান রেটিং জমা হয়েছে।',
  TKeys.reportTechnician:       'টেকনিশিয়ানের নামে অভিযোগ করুন',
  TKeys.complaintTitle:         'অভিযোগের শিরোনাম',
  TKeys.complaintReason:        'সমস্যাটি বর্ণনা করুন',
  TKeys.complaintSubmitted:     'অভিযোগ জমা হয়েছে',
  TKeys.complaintSubmittedMsg:  'আপনার অভিযোগ পর্যালোচনার জন্য জমা দেওয়া হয়েছে।',
  TKeys.deletePortfolioConfirm: 'পোর্টফোলিও কাজ মুছে ফেলবেন?',
  TKeys.tapToSelectImage:       'ছবি নির্বাচন করতে ট্যাপ করুন',
  TKeys.next:                   'পরবর্তী',
  TKeys.bdt:                    'টাকা',

  // My Bookings / Orders / Services
  TKeys.myBookings:             'আমার বুকিং',
  TKeys.noBookingsFound:        'কোনো বুকিং পাওয়া যায়নি',
  TKeys.previousOrders:         'পূর্ববর্তী অর্ডার',
  TKeys.noPreviousOrders:       'কোনো পূর্ববর্তী অর্ডার পাওয়া যায়নি',
  TKeys.viewDetails:            'বিস্তারিত দেখুন',
  TKeys.noServicesAvailable:    'কোনো সেবা উপলব্ধ নেই',

  // Service Details / Bidding
  TKeys.bidNow:                 'বিড করুন',
  TKeys.editBid:                'বিড সম্পাদনা',
  TKeys.myCurrentBid:          'আমার বর্তমান বিড',
  TKeys.updateBid:              'বিড আপডেট করুন',
  TKeys.editYourBid:            'আপনার বিড সম্পাদনা করুন',
  TKeys.viewProviderBids:       'প্রদানকারীর বিড দেখুন',
  TKeys.serviceNotFound:        'সেবা পাওয়া যায়নি',
  TKeys.noDescription:          'কোনো বিবরণ নেই',
  TKeys.tapToStart:             'শুরু করতে নিচের বোতামে চাপুন',
  TKeys.serviceProviderBids:    'সেবা প্রদানকারীর বিড',
  TKeys.compareOffers:          'অফার তুলনা করুন এবং আপনার অনুরোধের জন্য সেরা প্রদানকারী বেছে নিন।',
  TKeys.bidSubmitted:           'বিড জমা হয়েছে',
  TKeys.bidSubmittedMsg:        'আপনার বিড সফলভাবে জমা হয়েছে।',
  TKeys.bidUpdated:             'বিড আপডেট হয়েছে',
  TKeys.bidUpdatedMsg:          'আপনার বিড সফলভাবে আপডেট হয়েছে।',
  TKeys.placeYourBid:           'আপনার বিড দিন',
  TKeys.placeBidSubtitle:       'এই সেবার অনুরোধের জন্য আপনার মূল্য এবং আনুমানিক আগমন সময় জমা দিন।',
  TKeys.enterBidPriceError:     'অনুগ্রহ করে আপনার বিড মূল্য দিন',
  TKeys.bidPrice:               'বিড মূল্য',
  TKeys.enterPrice:             'আপনার মূল্য লিখুন',
  TKeys.selectEstimatedTimeError:'অনুগ্রহ করে আনুমানিক সময় নির্বাচন করুন',
  TKeys.estimatedArrival:       'আনুমানিক আগমন সময়',
  TKeys.note:                   'নোট',
  TKeys.noteHint:               'গ্রাহকের জন্য একটি সংক্ষিপ্ত বার্তা যোগ করুন',
  TKeys.submitBid:              'বিড জমা দিন',
  TKeys.ratings:                'রেটিং',
  TKeys.noReviewsYet:           'এখনো কোনো রিভিউ নেই',
  TKeys.ratingsAndReviews:      'রেটিং ও রিভিউ',
  TKeys.failedToLoadPage:       'পেজটি লোড করা যায়নি। আপনার সংযোগ পরীক্ষা করুন।',
  TKeys.reply:                  'উত্তর',
  TKeys.writeReply:             'একটি উত্তর লিখুন...',

  // Category Details
  TKeys.categoryDetails:        'ক্যাটাগরির বিবরণ',
  TKeys.categoryNotFound:       'ক্যাটাগরি পাওয়া যায়নি',
  TKeys.clicks:                 'ক্লিক',
  TKeys.noServicesInCategory:   'এই ক্যাটাগরির জন্য কোনো সেবা উপলব্ধ নেই',
  TKeys.untitledService:        'শিরোনামহীন সেবা',

  // Menu
  TKeys.menuTitle:              'মেনু',
  TKeys.portfolio:              'পোর্টফোলিও',
  TKeys.rewards:                'পুরস্কার',
  TKeys.customerSupport:        'গ্রাহক সহায়তা',
  TKeys.privacyPolicy:          'গোপনীয়তা নীতি',
  TKeys.termsConditions:        'শর্তাবলী',
  TKeys.logout:                 'লগ আউট',
  TKeys.logoutConfirm:          'আপনি কি নিশ্চিত লগ আউট করতে চান?',

  // Customer Support
  TKeys.subject:                'বিষয়',
  TKeys.subjectRequired:        'বিষয় আবশ্যক',
  TKeys.messageLabel:           'বার্তা',
  TKeys.messageRequired:        'বার্তা আবশ্যক',
  TKeys.faq:                    'সাধারণ প্রশ্ন',
  TKeys.frequentlyAskedQuestions: 'সাধারণত জিজ্ঞাসিত প্রশ্ন',
  TKeys.noFaqsAvailable:        'কোনো প্রশ্ন পাওয়া যায়নি',
  TKeys.supportSubmitted:       'টিকেট জমা হয়েছে',
  TKeys.supportSubmittedMsg:    'আপনার অনুরোধ পেয়েছি, শীঘ্রই যোগাযোগ করব।',
  TKeys.supportTicket:          'সাপোর্ট টিকেট',

  // Statistics
  TKeys.statistics:             'পরিসংখ্যান',
  TKeys.totalJobs:              'মোট কাজ',
  TKeys.weeklyEarnings:         'সাপ্তাহিক আয়',
  TKeys.weeklyEarningsSubtitle: 'এই সপ্তাহের আয়ের সারসংক্ষেপ',
  TKeys.monthlyPerformance:     'মাসিক পারফরম্যান্স',
  TKeys.monthlyPerformanceSubtitle: 'মাস অনুযায়ী সম্পন্ন কাজ',

  // Portfolio
  TKeys.addWork:                'কাজ যোগ করুন',
  TKeys.pfBathroomCleaning:     'বাথরুম গভীর পরিষ্কার',
  TKeys.pfBathroomCleaningDesc: 'একটি আবাসিক অ্যাপার্টমেন্টের জন্য সম্পন্ন',
  TKeys.pfKitchenPlumbing:      'রান্নাঘরের পাইপ মেরামত',
  TKeys.pfKitchenPlumbingDesc:  'পাইপ লিকেজ সফলভাবে ঠিক করা হয়েছে',
  TKeys.pfWallPainting:         'দেয়াল রঙ করার সেবা',
  TKeys.pfWallPaintingDesc:     'সম্পূর্ণ রুম পুনরায় রঙ করা সম্পন্ন',

  // Rewards
  TKeys.totalRewardPoints:      'মোট পুরস্কার পয়েন্ট',
  TKeys.rewardPointsSubtitle:   'ছাড় এবং বিশেষ অফারের জন্য আপনার পয়েন্ট ব্যবহার করুন',
  TKeys.availableRewards:       'উপলভ্য পুরস্কার',
  TKeys.rewardUnlocked:         'আনলক করা হয়েছে',
  TKeys.rewardPointsToUnlock:   'পয়েন্ট প্রয়োজন',
  TKeys.noRewardsAvailable:     'এখনো কোনো পুরস্কার নেই',
  TKeys.howToEarnPoints:        'পয়েন্ট কীভাবে অর্জন করবেন',
  TKeys.rewardMilestones:       'পুরস্কার মাইলফলক',
  TKeys.nextMilestone:          'পরবর্তী মাইলফলক',
  TKeys.earnByProfile:          'আপনার প্রোফাইল সম্পূর্ণ করুন',
  TKeys.earnByBooking:          'একটি বুকিং সম্পন্ন করুন',
  TKeys.earnByComment:          'একটি মন্তব্য পোস্ট করুন',
  TKeys.earnByReply:            'মন্তব্যে উত্তর দিন',
  TKeys.earnByReview:           'সার্ভিস রিভিউ লিখুন',
  TKeys.earnByRating:           'টেকনিশিয়ানকে রেটিং দিন',
  TKeys.pts:                    'পয়েন্ট',
};
