import 'translation_keys.dart';

const Map<String, String> enUS = {
  // General
  TKeys.appName:           'Kaj Ache',
  TKeys.ok:                'OK',
  TKeys.cancel:            'Cancel',
  TKeys.save:              'Save',
  TKeys.edit:              'Edit',
  TKeys.delete:            'Delete',
  TKeys.confirm:           'Confirm',
  TKeys.back:              'Back',
  TKeys.retry:             'Retry',
  TKeys.loading:           'Loading...',
  TKeys.noData:            'No data found',
  TKeys.error:             'Error',
  TKeys.success:           'Success',
  TKeys.submit:            'Submit',
  TKeys.search:            'Search',
  TKeys.seeAll:            'See All',
  TKeys.district:            'District',
  TKeys.area:                'Area',
  TKeys.selectDistrict:      'Select district',
  TKeys.selectDistrictFirst: 'Select district first',
  TKeys.selectArea:          'Select area',
  TKeys.businessName:        'Business Name',
  TKeys.serviceCategory:     'Service Category',
  TKeys.experience:          'Experience',
  TKeys.serviceArea:         'Service Area',
  TKeys.saveChanges:         'Save Changes',

  // Auth
  TKeys.welcomeBack:      'Welcome back',
  TKeys.fullname:         'Full Name',
  TKeys.email:            'Email',
  TKeys.phone:            'Phone',
  TKeys.password:         'Password',
  TKeys.phoneNumber:      'Phone number',
  TKeys.forgotPassword:   'Forgot password?',
  TKeys.login:            'Login',
  TKeys.noAccount:        "Don't have an account?",
  TKeys.signUp:           'Sign up',
  TKeys.emailOrPhone:     'Email or Phone',
  TKeys.emailOrPhoneHint: 'Enter your email or phone number',
  TKeys.inputRequired:    'This field is required',
  TKeys.inputInvalid:     'Enter a valid email or phone number',
  TKeys.passwordRequired: 'Password is required',
  TKeys.passwordMin:      'Minimum 6 characters',
  TKeys.resetPassword:       'Reset Password',
  // Home
  TKeys.home:              'Home',
  TKeys.whatService:       'What service do you need?',
  TKeys.popularServices:   'Popular Services',
  TKeys.allCategories:     'All Categories',

  // Technician Dashboard
  TKeys.dashboardSubtitle: 'Manage your services and track your performance.',
  TKeys.todayOverview:     'Today Overview',
  TKeys.availableJobs:     'Available Jobs',
  TKeys.ongoing:           'Ongoing',
  TKeys.earnings:          'Earnings',
  TKeys.noAvailableJobs:   'No available jobs right now.\nPull down to refresh.',
  TKeys.recentActivities:  'Recent Activities',
  TKeys.customer:          'Customer',
  TKeys.customerBudget:    'Customer Budget',
  TKeys.request:           'request',
  TKeys.bids:              'bids',
  TKeys.noBidsYet:         'No bids yet',
  TKeys.bidPlaced:         'Bid Placed',
  TKeys.postedBy:          'Posted by',

  // Services
  TKeys.services:          'Services',
  TKeys.categories:        'Categories',
  TKeys.bookNow:           'Book Now',
  TKeys.serviceDetails:    'Service Details',
  TKeys.selectDate:        'Select Date',
  TKeys.selectTime:        'Select Time',
  TKeys.address:           'Address',
  TKeys.bookingConfirm:    'Confirm Booking',
  TKeys.bookingSuccess:    'Booking Successful!',

  // Orders
  TKeys.orders:            'Orders',
  TKeys.activeOrders:      'Active Orders',
  TKeys.pastOrders:        'Past Orders',
  TKeys.orderDetails:      'Order Details',
  TKeys.orderStatus:       'Order Status',
  TKeys.cancelOrder:       'Cancel Order',
  TKeys.pending:           'Pending',
  TKeys.accepted:          'Accepted',
  TKeys.onTheWay:          'On The Way',
  TKeys.inProgress:        'In Progress',
  TKeys.completed:         'Completed',
  TKeys.cancelled:         'Cancelled',

  // Tracking
  TKeys.trackOrder:        'Track Order',
  TKeys.workerOnTheWay:    'Worker is on the way',

  // Chat
  TKeys.chat:              'Chat',
  TKeys.messages:          'Messages',
  TKeys.typeMessage:       'Type a message...',
  TKeys.send:              'Send',

  // Payments
  TKeys.payment:           'Payment',
  TKeys.paymentMethod:     'Payment Method',
  TKeys.totalAmount:       'Total Amount',
  TKeys.transactions:      'Transactions',
  TKeys.cash:              'Cash',
  TKeys.bkash:             'bKash',
  TKeys.nagad:             'Nagad',

  // Reviews
  TKeys.reviews:           'Reviews',
  TKeys.writeReview:       'Write a Review',
  TKeys.rating:            'Rating',
  TKeys.yourReview:        'Your Review',

  // Notifications
  TKeys.notifications:     'Notifications',
  TKeys.markAllRead:       'Mark All as Read',
  TKeys.noNotifications:   'No notifications yet',

  // Profile
  TKeys.profile:           'Profile',
  TKeys.editProfile:       'Edit Profile',
  TKeys.myProfile:         'My Profile',
  TKeys.workerProfile:     'Worker Profile',
  TKeys.language:          'Language',
  TKeys.theme:             'Theme',
  TKeys.darkMode:          'Dark Mode',
  TKeys.lightMode:         'Light Mode',
  TKeys.settings:          'Settings',

  // Auth (extended)
  TKeys.passwordResetSuccess:   'Your password has been reset successfully.',
  TKeys.createNewPassword:      'Create a new password for your account.',
  TKeys.newPassword:            'New Password',
  TKeys.newPasswordRequired:    'New password is required',
  TKeys.confirmPassword:        'Confirm Password',
  TKeys.confirmPasswordRequired:'Confirm password is required',
  TKeys.passwordsDoNotMatch:    'Passwords do not match',
  TKeys.enterOtp:               'Please enter the 6-digit OTP',
  TKeys.accountVerified:        'Your account has been verified successfully.',
  TKeys.verifyOtp:              'Verify OTP',
  TKeys.otpSentInfo:            'Enter the 6-digit code sent to your phone or email.',
  TKeys.verify:                 'Verify',
  TKeys.resendOtp:              'Resend OTP',
  TKeys.createAccount:          'Create Account',
  TKeys.registerSubtitle:       'Register to continue using Kaj Ache',
  TKeys.accountType:            'Account Type',
  TKeys.buyer:                  'Buyer',
  TKeys.service:                'Service',
  TKeys.enterFullName:          'Enter your full name',
  TKeys.nameRequired:           'Name is required',
  TKeys.enterEmail:             'Enter your email',
  TKeys.emailRequired:          'Email is required',
  TKeys.enterValidEmail:        'Enter a valid email',
  TKeys.enterPhone:             'Enter your phone number',
  TKeys.phoneRequired:          'Phone number is required',
  TKeys.enterValidPhone:        'Enter a valid phone number',
  TKeys.haveAccount:            'Already have an account?',

  // Profile (extended)
  TKeys.completeProfile:        'Complete Profile',
  TKeys.saveProfile:            'Save Profile',
  TKeys.buyerAccount:           'Buyer Account',
  TKeys.serviceProvider:        'Service Provider',
  TKeys.basicInformation:       'Basic Information',
  TKeys.buyerDetails:           'Buyer Details',
  TKeys.jobsPosted:             'Jobs Posted',
  TKeys.totalSpent:             'Total Spent',
  TKeys.trustScore:             'Trust Score',
  TKeys.serviceProviderDetails: 'Service Provider Details',
  TKeys.category:               'Category',
  TKeys.completedJobs:          'Completed Jobs',

  // Booking
  TKeys.describeProblemError:   'Please describe your problem.',
  TKeys.addressRequired:        'Address is required.',
  TKeys.pickDateError:          'Please pick a date.',
  TKeys.selectTimeSlotError:    'Please select a time slot.',
  TKeys.budgetMinError:         'Set a budget of at least 100 BDT.',
  TKeys.validation:             'Validation',
  TKeys.bookingSuccessful:      'Booking Successful',
  TKeys.bookingSubmittedMsg:    'Your booking has been submitted successfully. Providers can now place bids on your request.',
  TKeys.viewMyBookings:         'View My Bookings',
  TKeys.bookService:            'Book Service',
  TKeys.serviceScope:           'Service Scope',
  TKeys.logistics:              'Logistics',
  TKeys.payConfirm:             'Pay & Confirm',
  TKeys.minimumPrice:           'Minimum Price',
  TKeys.defineScope:            'Define the Scope',
  TKeys.defineScopeSubtitle:    'Tell us exactly what you need done.',
  TKeys.selectSubservices:      'Select Subservices (optional)',
  TKeys.problemDetails:         'Problem Details *',
  TKeys.problemDetailsHint:     "Describe the problem in detail. The more you share, the better bids you'll receive...",
  TKeys.logisticsBudget:        'Logistics & Budget',
  TKeys.logisticsSubtitle:      'Where, when, and how much?',
  TKeys.serviceAddress:         'Service Address *',
  TKeys.addressHint:            'House #, Road, Area...',
  TKeys.city:                   'City',
  TKeys.dateLabel:              'Date *',
  TKeys.pickDate:               'Pick date',
  TKeys.pickTime:               'Pick time',
  TKeys.timeSlot:               'Time Slot *',
  TKeys.minBudgetError:         'Minimum budget is 100 BDT',
  TKeys.maxBudgetLabel:         'Maximum Budget (BDT) *',
  TKeys.budgetHint:             'e.g. 2000',
  TKeys.maxBudgetInfo:          "Providers won't bid above this amount.",
  TKeys.reviewPay:              'Review & Pay',
  TKeys.bookingFeeInfo:         'A small booking fee opens your request for bidding.',
  TKeys.maxBudgetShort:         'Max Budget',
  TKeys.bookingFee:             'Booking Fee',
  TKeys.refundableInfo:         'Refundable if no provider is found',
  TKeys.processing:             'Processing...',
  TKeys.confirmPay500:          'Confirm & Pay 500 BDT',
  TKeys.next:                   'Next',
  TKeys.bdt:                    'BDT',

  // My Bookings / Orders / Services
  TKeys.myBookings:             'My Bookings',
  TKeys.noBookingsFound:        'No bookings found',
  TKeys.previousOrders:         'Previous Orders',
  TKeys.noPreviousOrders:       'No previous orders found',
  TKeys.viewDetails:            'View Details',
  TKeys.noServicesAvailable:    'No services available',

  // Service Details / Bidding
  TKeys.bidNow:                 'Bid Now',
  TKeys.editBid:                'Edit Bid',
  TKeys.myCurrentBid:          'My Current Bid',
  TKeys.updateBid:              'Update Bid',
  TKeys.editYourBid:            'Edit Your Bid',
  TKeys.viewProviderBids:       'View Provider Bids',
  TKeys.serviceNotFound:        'Service not found',
  TKeys.noDescription:          'No description available',
  TKeys.tapToStart:             'Tap the button below to get started',
  TKeys.serviceProviderBids:    'Service Provider Bids',
  TKeys.compareOffers:          'Compare offers and choose the best provider for your request.',
  TKeys.bidSubmitted:           'Bid Submitted',
  TKeys.bidSubmittedMsg:        'Your bid has been submitted successfully.',
  TKeys.bidUpdated:             'Bid Updated',
  TKeys.bidUpdatedMsg:          'Your bid has been updated successfully.',
  TKeys.placeYourBid:           'Place Your Bid',
  TKeys.placeBidSubtitle:       'Submit your price and estimated arrival time for this service request.',
  TKeys.enterBidPriceError:     'Please enter your bid price',
  TKeys.bidPrice:               'Bid Price',
  TKeys.enterPrice:             'Enter your price',
  TKeys.selectEstimatedTimeError:'Please select estimated time',
  TKeys.estimatedArrival:       'Estimated Arrival Time',
  TKeys.note:                   'Note',
  TKeys.noteHint:               'Add a short message for the customer',
  TKeys.submitBid:              'Submit Bid',

  // Category Details
  TKeys.categoryDetails:        'Category Details',
  TKeys.categoryNotFound:       'Category not found',
  TKeys.clicks:                 'clicks',
  TKeys.noServicesInCategory:   'No services available for this category',
  TKeys.untitledService:        'Untitled service',

  // Menu
  TKeys.menuTitle:              'Menu',
  TKeys.portfolio:              'Portfolio',
  TKeys.rewards:                'Rewards',
  TKeys.customerSupport:        'Customer Support',
  TKeys.privacyPolicy:          'Privacy Policy',
  TKeys.termsConditions:        'Terms & Conditions',
  TKeys.logout:                 'Log Out',
  TKeys.logoutConfirm:          'Are you sure you want to log out?',

  // Customer Support
  TKeys.subject:                'Subject',
  TKeys.subjectRequired:        'Subject is required',
  TKeys.messageLabel:           'Message',
  TKeys.messageRequired:        'Message is required',

  // Statistics
  TKeys.statistics:             'Statistics',
  TKeys.totalJobs:              'Total Jobs',
  TKeys.weeklyEarnings:         'Weekly Earnings',
  TKeys.weeklyEarningsSubtitle: 'This week earnings overview',
  TKeys.monthlyPerformance:     'Monthly Performance',
  TKeys.monthlyPerformanceSubtitle: 'Jobs completed by month',

  // Portfolio
  TKeys.addWork:                'Add Work',
  TKeys.pfBathroomCleaning:     'Bathroom Deep Cleaning',
  TKeys.pfBathroomCleaningDesc: 'Completed for a residential apartment',
  TKeys.pfKitchenPlumbing:      'Kitchen Plumbing Repair',
  TKeys.pfKitchenPlumbingDesc:  'Pipe leakage fixed successfully',
  TKeys.pfWallPainting:         'Wall Painting Service',
  TKeys.pfWallPaintingDesc:     'Full room repaint completed',

  // Rewards
  TKeys.totalRewardPoints:      'Total Reward Points',
  TKeys.rewardPointsSubtitle:   'Use your points for discounts and special offers',
  TKeys.rewardHistory:          'Reward History',
  TKeys.rwOrderBonus:           'Order Completed Bonus',
  TKeys.rwReferral:             'Referral Reward',
  TKeys.rwFirstBooking:         'First Booking Reward',
  TKeys.rwCampaign:             'Special Campaign Bonus',
};
