import 'translation_keys.dart';

const Map<String, String> enUS = {
  // General
  TKeys.appName:           'Kaj Ache',
  TKeys.ok:                'OK',
  TKeys.cancel:            'Cancel',
  TKeys.save:              'Save',
  TKeys.edit:              'Edit',
  TKeys.delete:            'Delete',
  TKeys.confirm:           'Confirm',
  TKeys.back:              'Back',
  TKeys.retry:             'Retry',
  TKeys.tryAgain:          'Try Again',
  TKeys.change:            'Change',
  TKeys.close:             'Close',
  TKeys.thankYou:          'Thank You',
  TKeys.starRating:        'star',
  TKeys.warning:           'Warning',
  TKeys.enterCommentFirst: 'Please enter a comment before submitting.',
  TKeys.commentPosted:     'Comment posted successfully!',
  TKeys.enterReplyFirst:   'Please enter a reply before submitting.',
  TKeys.replyPosted:       'Reply posted successfully!',
  TKeys.loading:           'Loading...',
  TKeys.noData:            'No data found',
  TKeys.error:             'Error',
  TKeys.success:           'Success',
  TKeys.submit:            'Submit',
  TKeys.search:            'Search',
  TKeys.seeAll:            'See All',
  TKeys.district:            'District',
  TKeys.area:                'Area',
  TKeys.selectDistrict:      'Select district',
  TKeys.selectDistrictFirst: 'Select district first',
  TKeys.selectArea:          'Select area',
  TKeys.businessName:        'Business Name',
  TKeys.serviceCategory:     'Service Category',
  TKeys.experience:          'Experience',
  TKeys.serviceArea:         'Service Area',
  TKeys.saveChanges:         'Save Changes',

  // Auth
  TKeys.welcomeBack:      'Welcome back',
  TKeys.fullname:         'Full Name',
  TKeys.email:            'Email',
  TKeys.phone:            'Phone',
  TKeys.password:         'Password',
  TKeys.phoneNumber:      'Phone number',
  TKeys.forgotPassword:   'Forgot password?',
  TKeys.login:            'Login',
  TKeys.noAccount:        "Don't have an account?",
  TKeys.signUp:           'Sign up',
  TKeys.emailOrPhone:     'Email or Phone',
  TKeys.emailOrPhoneHint: 'Enter your email or phone number',
  TKeys.inputRequired:    'This field is required',
  TKeys.inputInvalid:     'Enter a valid email or phone number',
  TKeys.passwordRequired: 'Password is required',
  TKeys.passwordMin:      'Minimum 6 characters',
  TKeys.resetPassword:       'Reset Password',
  // Home
  TKeys.home:              'Home',
  TKeys.whatService:       'What service do you need?',
  TKeys.popularServices:   'Popular Services',
  TKeys.allCategories:     'All Categories',

  // Technician Dashboard
  TKeys.dashboardSubtitle: 'Manage your services and track your performance.',
  TKeys.todayOverview:     'Today Overview',
  TKeys.availableJobs:     'Available Jobs',
  TKeys.ongoing:           'Ongoing',
  TKeys.earnings:          'Earnings',
  TKeys.noAvailableJobs:   'No available jobs right now.\nPull down to refresh.',
  TKeys.recentActivities:  'Recent Activities',
  TKeys.customer:          'Customer',
  TKeys.customerBudget:    'Customer Budget',
  TKeys.request:           'request',
  TKeys.bids:              'bids',
  TKeys.noBidsYet:         'No bids yet',
  TKeys.bidPlaced:         'Bid Placed',
  TKeys.postedBy:          'Posted by',

  // Services
  TKeys.services:          'Services',
  TKeys.categories:        'Categories',
  TKeys.bookNow:           'Book Now',
  TKeys.serviceDetails:    'Service Details',
  TKeys.selectDate:        'Select Date',
  TKeys.selectTime:        'Select Time',
  TKeys.address:           'Address',
  TKeys.bookingConfirm:    'Confirm Booking',
  TKeys.bookingSuccess:    'Booking Successful!',

  // Orders
  TKeys.orders:            'Orders',
  TKeys.activeOrders:      'Active Orders',
  TKeys.pastOrders:        'Past Orders',
  TKeys.orderDetails:      'Order Details',
  TKeys.orderStatus:       'Order Status',
  TKeys.cancelOrder:       'Cancel Order',
  TKeys.pending:           'Pending',
  TKeys.accepted:          'Accepted',
  TKeys.onTheWay:          'On The Way',
  TKeys.inProgress:        'In Progress',
  TKeys.completed:         'Completed',
  TKeys.cancelled:         'Cancelled',

  // Tracking
  TKeys.trackOrder:        'Track Order',
  TKeys.workerOnTheWay:    'Worker is on the way',

  // Chat
  TKeys.chat:              'Chat',
  TKeys.messages:          'Messages',
  TKeys.typeMessage:       'Type a message...',
  TKeys.send:              'Send',

  // Payments
  TKeys.payment:           'Payment',
  TKeys.paymentMethod:     'Payment Method',
  TKeys.totalAmount:       'Total Amount',
  TKeys.platformFee:       'Platform Fee',
  TKeys.jobBudget:         'Job Budget',
  TKeys.payNow:            'Pay Now',
  TKeys.couponCode:        'Coupon Code',
  TKeys.applyCoupon:       'Apply',
  TKeys.tapToApply:        'Tap to apply',
  TKeys.invalidCoupon:     'Invalid or expired coupon code.',
  TKeys.couponApplied:     'Coupon applied!',
  TKeys.discount:          'Discount',
  TKeys.removeCoupon:      'Remove',
  TKeys.availableCoupons:  'Available Coupons',
  TKeys.transactions:      'Transactions',
  TKeys.cash:              'Cash',
  TKeys.bkash:             'bKash',
  TKeys.nagad:             'Nagad',

  // Reviews
  TKeys.reviews:           'Reviews',
  TKeys.writeReview:       'Write a Review',
  TKeys.rating:            'Rating',
  TKeys.yourReview:        'Your Review',

  // Notifications
  TKeys.notifications:     'Notifications',
  TKeys.markAllRead:       'Mark All as Read',
  TKeys.noNotifications:   'No notifications yet',

  // Profile
  TKeys.profile:           'Profile',
  TKeys.editProfile:       'Edit Profile',
  TKeys.myProfile:         'My Profile',
  TKeys.workerProfile:     'Worker Profile',
  TKeys.language:          'Language',
  TKeys.theme:             'Theme',
  TKeys.darkMode:          'Dark Mode',
  TKeys.lightMode:         'Light Mode',
  TKeys.settings:          'Settings',

  // Auth (extended)
  TKeys.passwordResetSuccess:   'Your password has been reset successfully.',
  TKeys.createNewPassword:      'Create a new password for your account.',
  TKeys.newPassword:            'New Password',
  TKeys.newPasswordRequired:    'New password is required',
  TKeys.confirmPassword:        'Confirm Password',
  TKeys.confirmPasswordRequired:'Confirm password is required',
  TKeys.passwordsDoNotMatch:    'Passwords do not match',
  TKeys.enterOtp:               'Please enter the 6-digit OTP',
  TKeys.accountVerified:        'Your account has been verified successfully.',
  TKeys.verifyOtp:              'Verify OTP',
  TKeys.otpSentInfo:            'Enter the 6-digit code sent to your phone or email.',
  TKeys.verify:                 'Verify',
  TKeys.resendOtp:              'Resend OTP',
  TKeys.createAccount:          'Create Account',
  TKeys.registerSubtitle:       'Register to continue using Kaj Ache',
  TKeys.accountType:            'Account Type',
  TKeys.buyer:                  'Buyer',
  TKeys.service:                'Service',
  TKeys.enterFullName:          'Enter your full name',
  TKeys.nameRequired:           'Name is required',
  TKeys.enterEmail:             'Enter your email',
  TKeys.emailRequired:          'Email is required',
  TKeys.enterValidEmail:        'Enter a valid email',
  TKeys.enterPhone:             'Enter your phone number',
  TKeys.phoneRequired:          'Phone number is required',
  TKeys.enterValidPhone:        'Enter a valid phone number',
  TKeys.haveAccount:            'Already have an account?',

  // Profile (extended)
  TKeys.completeProfile:        'Complete Profile',
  TKeys.saveProfile:            'Save Profile',
  TKeys.buyerAccount:           'Buyer Account',
  TKeys.serviceProvider:        'Service Provider',
  TKeys.basicInformation:       'Basic Information',
  TKeys.buyerDetails:           'Buyer Details',
  TKeys.jobsPosted:             'Jobs Posted',
  TKeys.totalSpent:             'Total Spent',
  TKeys.trustScore:             'Trust Score',
  TKeys.serviceProviderDetails: 'Service Provider Details',
  TKeys.category:               'Category',
  TKeys.completedJobs:          'Completed Jobs',

  // Booking
  TKeys.describeProblemError:   'Please describe your problem.',
  TKeys.addressRequired:        'Address is required.',
  TKeys.pickDateError:          'Please pick a date.',
  TKeys.selectTimeSlotError:    'Please select a time slot.',
  TKeys.budgetMinError:         'Set a budget of at least 100 BDT.',
  TKeys.validation:             'Validation',
  TKeys.bookingSuccessful:      'Booking Successful',
  TKeys.bookingSubmittedMsg:    'Your booking has been submitted successfully. Providers can now place bids on your request.',
  TKeys.viewMyBookings:         'View My Bookings',
  TKeys.bookService:            'Book Service',
  TKeys.serviceScope:           'Service Scope',
  TKeys.logistics:              'Logistics',
  TKeys.payConfirm:             'Pay & Confirm',
  TKeys.minimumPrice:           'Minimum Price',
  TKeys.defineScope:            'Define the Scope',
  TKeys.defineScopeSubtitle:    'Tell us exactly what you need done.',
  TKeys.selectSubservices:      'Select Subservices (optional)',
  TKeys.problemDetails:         'Problem Details *',
  TKeys.problemDetailsHint:     "Describe the problem in detail. The more you share, the better bids you'll receive...",
  TKeys.logisticsBudget:        'Logistics & Budget',
  TKeys.logisticsSubtitle:      'Where, when, and how much?',
  TKeys.serviceAddress:         'Service Address *',
  TKeys.addressHint:            'House #, Road, Area...',
  TKeys.city:                   'City',
  TKeys.dateLabel:              'Date *',
  TKeys.pickDate:               'Pick date',
  TKeys.pickTime:               'Pick time',
  TKeys.timeSlot:               'Time Slot *',
  TKeys.minBudgetError:         'Minimum budget is 100 BDT',
  TKeys.transactionId:          'Transaction ID',
  TKeys.transactionIdHint:      'Enter your payment transaction ID',
  TKeys.transactionIdRequired:  'Transaction ID is required',
  TKeys.maxBudgetLabel:         'Maximum Budget (BDT) *',
  TKeys.budgetHint:             'e.g. 2000',
  TKeys.maxBudgetInfo:          "Providers won't bid above this amount.",
  TKeys.reviewPay:              'Review & Pay',
  TKeys.bookingFeeInfo:         'Pay the booking fee once you have selected a technician.',
  TKeys.maxBudgetShort:         'Max Budget',
  TKeys.bookingFee:             'Booking Fee',
  TKeys.refundableInfo:         'Refundable if no provider is found',
  TKeys.processing:             'Processing...',
  TKeys.confirmPay500:          'Confirm & Pay',
  TKeys.markTaskComplete:       'Mark task as completed?',
  TKeys.startBookingConfirm:    'Start this booking?',
  TKeys.makeInProgress:         'Make In Progress',
  TKeys.taskCompleted:          'Task Completed',
  TKeys.cashAfterService:       'Cash After Service',
  TKeys.markCashReceived:       'Mark Cash Received',
  TKeys.cashReceivedConfirmed:  'Cash receipt confirmed.',
  TKeys.cashPending:            'Cash Pending',
  TKeys.taskCompletedMsg:       'The booking has been marked as completed.',
  TKeys.technicianBooked:       'Technician booked successfully',
  TKeys.bookingIdMissing:       'Booking ID is missing.',
  TKeys.reviewService:          'Review Service',
  TKeys.rateTechnician:         'Rate Technician',
  TKeys.serviceReviewSubmitted: 'Your service review was submitted.',
  TKeys.techRatingSubmitted:    'Your technician rating was submitted.',
  TKeys.reportTechnician:       'Report Technician',
  TKeys.complaintTitle:         'Complaint title',
  TKeys.complaintReason:        'Describe the issue',
  TKeys.complaintSubmitted:     'Complaint submitted',
  TKeys.complaintSubmittedMsg:  'Your complaint has been submitted for review.',
  TKeys.deletePortfolioConfirm: 'Delete portfolio work?',
  TKeys.tapToSelectImage:       'Tap to select an image',
  TKeys.coverImage:             'Cover Image',
  TKeys.next:                   'Next',
  TKeys.bdt:                    'BDT',

  // My Bookings / Orders / Services
  TKeys.myBookings:             'My Bookings',
  TKeys.noBookingsFound:        'No bookings found',
  TKeys.previousOrders:         'Previous Orders',
  TKeys.noPreviousOrders:       'No previous orders found',
  TKeys.viewDetails:            'View Details',
  TKeys.noServicesAvailable:    'No services available',

  TKeys.postInstantService:       'Post Instant Service',
  TKeys.myInstantServices:        'My Instant Services',
  TKeys.availableInstantServices: 'Instant Jobs',
  TKeys.postRecruitmentRequest:   'Hire a Technician',
  TKeys.myRecruitmentRequests:    'My Job Posts',
  TKeys.availableRecruitmentRequests: 'Job Openings',

  TKeys.recruitmentDetailsLabel:     'Job Details',
  TKeys.recruitmentDetailsHint:      'Describe the role, responsibilities and requirements',
  TKeys.durationLabel:               'Duration',
  TKeys.durationHint:                'e.g. 3 months, Permanent',
  TKeys.salaryLabel:                 'Salary',
  TKeys.salaryHint:                  'e.g. 15000',
  TKeys.payToPost:                   'Pay to Post',
  TKeys.payToPostSubtitle:           'Pay the platform fee to open bidding for this job.',
  TKeys.recruitmentPosted:           'Job Posted',
  TKeys.recruitmentPostedMsg:        'Your job post is now live and technicians can apply.',
  TKeys.recruitmentPaymentFailedMsg: 'Job created, but payment failed. Pay from My Job Posts to open bidding.',
  TKeys.viewMyJobPosts:              'View My Job Posts',
  TKeys.noJobPostsFound:             'No job posts yet',
  TKeys.noOpenJobsFound:             'No open job posts yet',
  TKeys.proposedSalaryLabel:         'Proposed Salary',
  TKeys.proposedSalaryHint:          'e.g. 18000',
  TKeys.applicationMessageLabel:     'Message (optional)',
  TKeys.applicationMessageHint:      'Tell the client why you are a good fit',
  TKeys.applyNow:                    'Apply Now',
  TKeys.updateApplication:           'Update Application',
  TKeys.applicationSubmitted:        'Application Submitted',
  TKeys.applicationSubmittedMsg:     'Your application has been sent to the client.',
  TKeys.applicationUpdated:          'Application Updated',
  TKeys.hireApplicant:               'Hire',
  TKeys.hiredSuccessfully:           'Hired',
  TKeys.hiredSuccessfullyMsg:        'You have hired this applicant.',
  TKeys.endEngagement:               'End Engagement',
  TKeys.engagementEnded:             'Engagement ended.',
  TKeys.cancelJobPost:               'Cancel Job Post',
  TKeys.jobPostCancelled:            'Job post cancelled.',
  TKeys.recruitmentDetailsTitle:     'Job Post Details',
  TKeys.applicantsLabel:             'Applicants',
  TKeys.instantServiceTitleLabel:  'Job Title',
  TKeys.instantServiceTitleHint:   'e.g. Fix a leaking tap',
  TKeys.priceMin:                  'Minimum Price',
  TKeys.priceMax:                  'Maximum Price',
  TKeys.priceRangeHint:            'e.g. 500',
  TKeys.invalidPriceRangeError:    'Maximum price must be greater than minimum price',
  TKeys.instantServiceSubmitted:     'Instant Service Posted',
  TKeys.instantServiceSubmittedMsg:  'Technicians can now bid on your job.',
  TKeys.noInstantServicesFound:    'No instant services yet',
  TKeys.selectBidder:              'Select Bidder',
  TKeys.acceptJob:                 'Accept Job',
  TKeys.cancelInstantService:      'Cancel Instant Service',
  TKeys.instantServiceDetailsTitle: 'Instant Service Details',

  // Service Details / Bidding
  TKeys.bidNow:                 'Bid Now',
  TKeys.editBid:                'Edit Bid',
  TKeys.myCurrentBid:          'My Current Bid',
  TKeys.updateBid:              'Update Bid',
  TKeys.editYourBid:            'Edit Your Bid',
  TKeys.viewProviderBids:       'View Provider Bids',
  TKeys.serviceNotFound:        'Service not found',
  TKeys.noDescription:          'No description available',
  TKeys.tapToStart:             'Tap the button below to get started',
  TKeys.serviceProviderBids:    'Service Provider Bids',
  TKeys.compareOffers:          'Compare offers and choose the best provider for your request.',
  TKeys.bidSubmitted:           'Bid Submitted',
  TKeys.bidSubmittedMsg:        'Your bid has been submitted successfully.',
  TKeys.bidUpdated:             'Bid Updated',
  TKeys.bidUpdatedMsg:          'Your bid has been updated successfully.',
  TKeys.placeYourBid:           'Place Your Bid',
  TKeys.placeBidSubtitle:       'Submit your price and estimated arrival time for this service request.',
  TKeys.enterBidPriceError:     'Please enter your bid price',
  TKeys.bidPrice:               'Bid Price',
  TKeys.enterPrice:             'Enter your price',
  TKeys.selectEstimatedTimeError:'Please select estimated time',
  TKeys.estimatedArrival:       'Estimated Arrival Time',
  TKeys.note:                   'Note',
  TKeys.noteHint:               'Add a short message for the customer',
  TKeys.submitBid:              'Submit Bid',
  TKeys.ratings:                'Ratings',
  TKeys.noReviewsYet:           'No reviews yet',
  TKeys.ratingsAndReviews:      'Ratings & Reviews',
  TKeys.failedToLoadPage:       'Failed to load the page. Please check your connection.',
  TKeys.reply:                  'Reply',
  TKeys.writeReply:             'Write a reply...',

  // Category Details
  TKeys.categoryDetails:        'Category Details',
  TKeys.categoryNotFound:       'Category not found',
  TKeys.clicks:                 'clicks',
  TKeys.noServicesInCategory:   'No services available for this category',
  TKeys.untitledService:        'Untitled service',

  // Menu
  TKeys.menuTitle:              'Menu',
  TKeys.portfolio:              'Portfolio',
  TKeys.rewards:                'Rewards',
  TKeys.customerSupport:        'Customer Support',
  TKeys.privacyPolicy:          'Privacy Policy',
  TKeys.termsConditions:        'Terms & Conditions',
  TKeys.aboutUs:                'About Us',
  TKeys.supportChat:            'Support Chat',
  TKeys.logout:                 'Log Out',
  TKeys.logoutConfirm:          'Are you sure you want to log out?',

  // About Us
  TKeys.noSocialMediaAvailable: 'No social media links available',
  TKeys.aboutUsTagline:  'Kaj Ache — Need Work Done',
  TKeys.aboutUsTitle:    'About Us',
  TKeys.aboutUsBody:     'Kaj Ache is Bangladesh\'s trusted home services marketplace — connecting skilled technicians with customers who need quality work done. From electrical repairs to plumbing, cleaning to appliance servicing, we make it easy to find reliable professionals near you.',
  TKeys.ourMission:      'Our Mission',
  TKeys.ourMissionBody:  'To empower local service providers with technology and provide customers with transparent, affordable, and safe home services — building trust one job at a time.',
  TKeys.contactTitle:    'Contact',
  TKeys.contactBody:     'Email: support@kajache.com\nPhone: +880 1800 000000\nWebsite: www.kajache.com',
  TKeys.followUs:        'Follow Us',
  TKeys.appVersion:      'v1.0.0 · © 2025 Kaj Ache',
  TKeys.couldNotOpenLink:       'Could not open link',

  // Customer Support
  TKeys.subject:                'Subject',
  TKeys.subjectRequired:        'Subject is required',
  TKeys.messageLabel:           'Message',
  TKeys.messageRequired:        'Message is required',
  TKeys.faq:                    'FAQ',
  TKeys.frequentlyAskedQuestions: 'Frequently Asked Questions',
  TKeys.noFaqsAvailable:        'No FAQs available',
  TKeys.supportSubmitted:       'Ticket Submitted',
  TKeys.supportSubmittedMsg:    'We received your request and will get back to you soon.',
  TKeys.supportTicket:          'Support Ticket',

  // Statistics
  TKeys.statistics:             'Statistics',
  TKeys.totalJobs:              'Total Jobs',
  TKeys.weeklyEarnings:         'Weekly Earnings',
  TKeys.weeklyEarningsSubtitle: 'This week earnings overview',
  TKeys.monthlyPerformance:     'Monthly Performance',
  TKeys.monthlyPerformanceSubtitle: 'Jobs completed by month',

  // Portfolio
  TKeys.addWork:                'Add Work',
  TKeys.pfBathroomCleaning:     'Bathroom Deep Cleaning',
  TKeys.pfBathroomCleaningDesc: 'Completed for a residential apartment',
  TKeys.pfKitchenPlumbing:      'Kitchen Plumbing Repair',
  TKeys.pfKitchenPlumbingDesc:  'Pipe leakage fixed successfully',
  TKeys.pfWallPainting:         'Wall Painting Service',
  TKeys.pfWallPaintingDesc:     'Full room repaint completed',

  // Rewards
  TKeys.totalRewardPoints:      'Total Reward Points',
  TKeys.rewardPointsSubtitle:   'Use your points for discounts and special offers',
  TKeys.availableRewards:       'Available Rewards',
  TKeys.rewardUnlocked:         'Unlocked',
  TKeys.rewardPointsToUnlock:   'points to unlock',
  TKeys.noRewardsAvailable:     'No rewards available yet',
  TKeys.howToEarnPoints:        'How to Earn Points',
  TKeys.rewardMilestones:       'Reward Milestones',
  TKeys.nextMilestone:          'Next milestone',
  TKeys.earnByProfile:          'Complete your profile',
  TKeys.earnByBooking:          'Complete a booking',
  TKeys.earnByComment:          'Post a comment',
  TKeys.earnByReply:            'Reply to a comment',
  TKeys.earnByReview:           'Write a service review',
  TKeys.earnByRating:           'Rate a technician',
  TKeys.pts:                    'pts',
};
